version: '3'
services:
  node-app:
    build: ./node-app
    container_name: node
    networks:
      - app-network
    depends_on:
      - db
 
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - node-app
    networks:
      - app-network
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=ON
    container_name: db
    restart: always
    tty: true
    volumes:
      - .mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
